In [2]:
import numpy as np

arr = np.array([[8, 3], [9, 1]])
print("Original flattened array:")
print(arr)
print("Maximum value of the above flattened array:", np.max(arr))
print("Minimum value of the above flattened array:", np.min(arr))

print("\n" + "-"*50 + "\n")

Original flattened array:
[[8 3]
 [9 1]]
Maximum value of the above flattened array: 9
Minimum value of the above flattened array: 1

--------------------------------------------------



In [4]:

array = np.array([1, 4, 9, 4])
print("Original array:", array)
float_array = array.astype(float)
print("Array converted to a float type:", float_array)

Original array: [1 4 9 4]
Array converted to a float type: [1. 4. 9. 4.]


In [10]:
matrix = np.arange(11,20).reshape(3, 3)
print("3x3 matrix with values ranging from 2 to 10:")
print(matrix)

print("\n" + "-"*50 + "\n")

3x3 matrix with values ranging from 2 to 10:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

--------------------------------------------------



In [27]:
%config InlineBackend.print_figure_kwargs = {'bbox_inches':None}
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

M1 = np.array([[5, 5],
               [1, 2]])  
M2 = np.array([[0, 1],
               [1, 0]])

resultant_matrix = np.dot(M1, M2)
transpose_matrix = resultant_matrix.T

print("Question 4:")
print("Matrix M1:\n", M1)
print("Matrix M2:\n", M2)
print("Resultant Matrix (M1 x M2):\n", resultant_matrix)
print("Transpose of Resultant Matrix:\n", transpose_matrix)
print("-" * 50)


Question 4:
Matrix M1:
 [[5 5]
 [1 2]]
Matrix M2:
 [[0 1]
 [1 0]]
Resultant Matrix (M1 x M2):
 [[5 5]
 [2 1]]
Transpose of Resultant Matrix:
 [[5 2]
 [5 1]]
--------------------------------------------------


In [28]:

A = np.array([[6, 1, 1, 3],
              [4, -2, 5, 1],
              [2, 8, 7, 6],
              [3, 1, 9, 7]])

# Find inverse of matrix A
A_inverse = np.linalg.inv(A)

print("Question 5:")
print("Matrix A:\n", A)
print("Inverse of Matrix A:\n", A_inverse)

# (Optional) Verify that A * A_inverse = Identity matrix
identity_check = np.dot(A, A_inverse)
print("\nVerification (A x A_inverse):\n", identity_check)

Question 5:
Matrix A:
 [[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
Inverse of Matrix A:
 [[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]

Verification (A x A_inverse):
 [[ 1.00000000e+00 -1.11022302e-16 -1.38777878e-17  2.77555756e-17]
 [ 8.32667268e-17  1.00000000e+00 -2.77555756e-17  3.33066907e-16]
 [ 1.11022302e-16 -2.22044605e-16  1.00000000e+00  2.77555756e-16]
 [ 0.00000000e+00 -1.11022302e-16 -1.38777878e-17  1.00000000e+00]]
